### ISSUE TITLE
ERROR454 - SHIVA3D

### ISSUE THREAD

**Issue by iricartb** [error454/ShiVa-Android-All-In-One#1]
Hello error454, sorry for introducing myself like this, but I am a Shiva3d developer and I have seen that the website has stopped giving support, do you know any way to obtain a license to be able to export? Thank you very much and sorry for the inconvenience caused.

**Comment by error454** [comment]
I haven't used shiva for many years. I saw their post today on shutting down the engine, licensing, etc. So it seems that if you weren't already an existing customer with an activated license that you may be out of luck. This is sad news.

**Comment by iricartb** [comment]
Thank you so much error454, no problem.
